### ISSUE TITLE
As a User, I would like to see other people's profile page so that I can see all of the tweets they have written so far.

### ISSUE THREAD

**Issue by jayohanna** [twatter-soen341/Twatter#167]
## Description
The profile page will show all of the selected user's tweets and information.

## Task Breakdown
- [x] Add routing to different user profiles (#164)
- [x] Fetch twats according to user ID (#165)
- [x] Add routerlink to user profile on posts (#166)
- [x] Add routerlink to user profile on search results and autocomplete (#172)
- [x] Add routerlink to user profile on comments (#173)
