### ISSUE TITLE
As a User, I want to attach a picture to my tweet so that I can share photos with my followers.

### ISSUE THREAD

**Issue by a-paggabao** [twatter-soen341/Twatter#193]
## Description
User can post a photo with their tweet.

## Task Breakdown
- [ ] Update Post model to support link to photo (#issue)
- [ ] Update Post-Create Service to store the link to photo (#issue)
- [ ] Modify tweet UI to add button/icon that can import photo (#issue)

**Comment by paulMoose** [comment]
Will no longer implement this user story; approved by TA.
