### ISSUE TITLE
As a User, I want to change my attached picture on my tweet.

### ISSUE THREAD

**Issue by a-paggabao** [twatter-soen341/Twatter#194]
## Description
User can change photo on their existing post/tweet with another photo.

## Task Breakdown
- [ ] Update Post-list Service to **change** link to photo (#issue)
- [ ] Update Post-list Service to **remove** link to photo (#issue)
- [ ] Modify Edit post dialog UI to add two button/icons that can edit/delete the post (#issue)

**Comment by paulMoose** [comment]
Will no longer implement this user story; approved by TA.
