### ISSUE TITLE
As a User, I would like to have a sidebar on my profile page so that I can see more information about my account

### ISSUE THREAD

**Issue by jayohanna** [twatter-soen341/Twatter#227]
## Description
The sidebar in the profile page will contain information about the user.

## Task Breakdown
- [x] Show following and followers (#223)
- [x] Add bio (#224)
- [x] Show age of account (#225)
- [x] Show twat score (#226)

**Comment by EtienneBerube** [comment]
Any update on this feature?
