### ISSUE TITLE
As a User, I want to create a tweet so that everyone who follows me can see.

### ISSUE THREAD

**Issue by Nichita-Hariton** [twatter-soen341/Twatter#25]
## [Core Feature: Posting a Tweet] 
The system should allow a user post content in the website. The content should be in the format of  text characters with a limit of 140 characters per post. These posts will then be visible for Twatter user.

## Task Breakdown 
- [x] Make a post model (UI and Mongoose) (#51) 
- [x] Make UI for how they appear on main page (#52)
- [x] Make the Post-Creator appealing and Aesthetic (#70)
- [x] Add post and get routes (#65)
- [x] Create Test (#53)

**Comment by EtienneBerube** [comment]
I'll take care of the post UI

**Comment by Nichita-Hariton** [comment]
I will take care of the post model and services

**Comment by EtienneBerube** [comment]
Update Alexandria already did the post and post creator components.

**Comment by a-paggabao** [comment]
Completed.
