### ISSUE TITLE
As a user, I want to follow/unfollow another user so that I can see their latest posts.

### ISSUE THREAD

**Issue by tarekait1996** [twatter-soen341/Twatter#63]
## Description
The system should allow an existing user to follow another user. User A will click a button "follow" in the profile page of user B. User A will then be able to see all posts from user B in his timeline.

## Task Breakdown
- [x] Update the User model to store followers (#98)
- [x] Create route to **Get** the "following" field of a user (#99)
- [x] Create route to **Update** the "following" field of a user (#100)
- [x] Add follow/unfollow buttons where necessary (#101)
- [x] Create tests for the backend routes (#53) 

## Risk: High

**Comment by EtienneBerube** [comment]
Optional for Sprint 2. Looking for Sprint 3 instead
