### ISSUE TITLE
As a User, I want to find other users in a "search by name" bar so that I can follow their posts.

### ISSUE THREAD

**Issue by Nichita-Hariton** [twatter-soen341/Twatter#72]
## Description
The search bar should have an autocomplete feature to display users from the DB. Clicking on it will lead to their profile, from which I can follow them.

## Task Breakdown
- [x] Separate user and auth models in the backend (#72)
- [x] Add route to search by name in the backend (#96)
- [x] Add UI search box to be used for any views (#97)

## Risk: Low

**Comment by a-paggabao** [comment]
Completed; all tasks are done.
