### ISSUE TITLE
As a user, I want to receive a notification if another user liked my Tweet.

### ISSUE THREAD

**Issue by paulMoose** [twatter-soen341/Twatter#82]
## Description
Once the user likes a tweet, the poster will receive a notification mentioning the user that liked it. Once viewed, the notification will disappear.

## Task Breakdown
- [x] Modify header to add notification icon (mat badge) (#93)
- [x] Create notification model (#94)
- [x] Add route to update read fields (#95)

## Risk: High

**Comment by EtienneBerube** [comment]
Shouldnt this be in Sprint 3?

**Comment by paulMoose** [comment]
> Shouldnt this be in Sprint 3?

Yes you are right

**Comment by tarekait1996** [comment]
I personally think notification should be an extra feature on its own and not attached to liking. We could create its own user stories. I suggest that we hold a meeting to discuss this further and get a general update on this story.

**Comment by a-paggabao** [comment]
> I personally think notification should be an extra feature on its own and not attached to liking. We could create its own user stories. I suggest that we hold a meeting to discuss this further and get a general update on this story.

Yes, I agree with you @tarekait1996! 
We will have some replanning to do to replace notification-related user stories, thus a meeting is mandatory.

**Comment by tarekait1996** [comment]
This user story will be separated from the liking core feature. Instead it will constitute its own feature alone and will be completed during our last sprint which is sprint 4.

**Comment by paulMoose** [comment]
Will no longer implement this user story; approved by TA.
